/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AICritiquePanel: typeof import('./src/components/AICritiquePanel.vue')['default']
    AIRewriteButton: typeof import('./src/components/AIRewriteButton.vue')['default']
    AssetImageGallery: typeof import('./src/components/AssetImageGallery.vue')['default']
    CardSkeleton: typeof import('./src/components/CardSkeleton.vue')['default']
    CollapsibleSection: typeof import('./src/components/CollapsibleSection.vue')['default']
    CritiqueDialog: typeof import('./src/components/CritiqueDialog.vue')['default']
    DirectionPicker: typeof import('./src/components/DirectionPicker.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    PlanCard: typeof import('./src/components/PlanCard.vue')['default']
    RoseBackdrop: typeof import('./src/components/RoseBackdrop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesGenerateDialog: typeof import('./src/components/SeriesGenerateDialog.vue')['default']
    ShotInsertSlot: typeof import('./src/components/ShotInsertSlot.vue')['default']
    StoryboardShotCard: typeof import('./src/components/StoryboardShotCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
