# Generated by Django 5.0.6 on 2026-04-28 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('target_platform', models.CharField(blank=True, max_length=32)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('update_frequency', models.CharField(blank=True, max_length=64)),
                ('episode_duration_seconds', models.IntegerField(default=60)),
                ('planned_episodes', models.IntegerField(default=0)),
                ('positioning', models.JSONField(blank=True, default=dict)),
                ('episode_template', models.JSONField(blank=True, default=dict)),
                ('visual_style', models.JSONField(blank=True, default=dict)),
                ('title_style', models.JSONField(blank=True, default=dict)),
                ('initial_topics', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ongoing', '连载中'), ('paused', '已暂停'), ('completed', '已完成')], default='draft', max_length=16)),
                ('characters', models.ManyToManyField(blank=True, related_name='series', to='assets.characterasset')),
                ('columns', models.ManyToManyField(blank=True, related_name='series', to='assets.columnasset')),
                ('styles', models.ManyToManyField(blank=True, related_name='series', to='assets.styleasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL)),
                ('worldviews', models.ManyToManyField(blank=True, related_name='series', to='assets.worldviewasset')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VideoPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('real', '不需要AI生成视频'), ('ai_generated', '需要AI生成视频')], max_length=16)),
                ('is_ai_generated_video', models.BooleanField(default=False)),
                ('target_platform', models.CharField(blank=True, max_length=32)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.IntegerField(default=30)),
                ('style', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('storyboard', models.JSONField(blank=True, default=list)),
                ('editing_advice', models.JSONField(blank=True, default=dict)),
                ('ai_prompts', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('optimizing', '优化中'), ('confirmed', '已确认'), ('completed', '已完成')], default='draft', max_length=16)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='plans.seriesplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
