# Generated by Django 5.0.6 on 2026-04-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aitask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aitask',
            new_name='ai_aitask_user_id_6959a8_idx',
            old_name='ai_aitask_user_id_fcb44f_idx',
        ),
        migrations.RenameIndex(
            model_name='aitask',
            new_name='ai_aitask_task_ty_1ae5f6_idx',
            old_name='ai_aitask_task_ty_b1d13f_idx',
        ),
    ]
